config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :lists do
  	resources :items
  end

  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :list 
	validates :name, presence: true
	
end

app/models/list.rb
class List < ApplicationRecord
	has_many :items, dependent: :destroy
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
	extend Devise::Models

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :lists, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	# skip_before_action :authenticate_user!
  def index
  	
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_list

  # def index
  # 	@item = @list.item.find(params[:id])
  # end

  def new
  	@item = Item.new
  end

  def create
  	@item = @list.items.new(item_params)
  	if @item.save 
  		redirect_to list_path(@list)
  	else
  		render :new
    end
  end

  def show
  	@item = @list.items.find(params[:id])
  end

  def edit
  	@item = @list.item.find(params[:id])
  end

  def update
  	@item = @list.items.find(params[:id])
		if @item.update(item_params)
			redirect_to list_item_path(@list, @item)
		else
			render :edit
		end
  end

  def destroy
  	@item = @list.items.find(params[:id])
		@item.destroy
		redirect_to list_path(@list)
  end

  private

  def find_list
  	@list = List.find(params[:list_id])
  end

  def item_params
  	params.require(:item).permit(:name, :description, :completed, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.where(user_id:current_user.id)
  end
 
  def show
  	@list = List.find(params[:id])
    # @items = @list.item
    @items = Item.where(list_id: params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.user_id = current_user.id
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)

      redirect_to list_path(@list)
    else
      render :edit
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:title, :place, :description, :completed, :user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/home/index.html.erb
<h1>Welcome to bucket list</h1>

<%= link_to 'create a list', new_list_path, class:"waves-effect waves-light btn" %>
<%= link_to 'All lists', lists_path, class:"waves-effect waves-light btn" %>


<h2>Welcome to Home#index </h2>

app/views/items/_item_form.html.erb
<% if @item.errors.any? %>
	<ul>
		<% @item.errors.full_messages.each do |error| %>
			<li><%= error %></li>
			<% end %>
	</ul>
<% end %>

<%= form_for [@list, @item] do |f| %>
	<%= f.label  :name %>
	<%= f.text_field :name %>
<br />
	<%= f.label :description %>
	<%= f.text_field :description %>
<br />
	<%= f.label :completed %>
	<%= f.text_field :completed %>
<br />
	<%= f.submit %>
<% end %>
<br />

app/views/items/edit.html.erb
<h1>edit the Item</h1>
<%= render(partial: 'item_form') %>

<%= link_to 'Back', list_path(@tripp) %>

app/views/items/index.html.erb
<h1>Items#index</h1>
<p>Find me in app/views/items/index.html.erb</p>

app/views/items/new.html.erb
<h1>new item</h1>

<%= render(partial: 'item_form') %>

<%= link_to 'Back', list_path(@list) %>

app/views/items/show.html.erb
iv class="hero">
  <nav>
    <div class="nav-wrapper">
      <div class="col s12">
        <a href= <%=lists_path %> class="breadcrumb">All items</a>
        <a href= <%=list_path(@list) %> class="breadcrumb">Second</a>
        <a href= <%=list_item_path %> class="breadcrumb">Third</a>
      </div>
    </div>
  </nav>




<h1><%= @item.name %></h1>
<h4><%= @item.category %></h4>



<div class="primary-footer">
  <%= link_to 'Edit List', edit_list_item_path(@list, @item), class:"waves-effect waves-light btn" %>
<% else %>
  <%= link_to 'Add item', new_list_item_address_path(@list, @item) %>
<% end %>

| <%= link_to 'Edit item', edit_list_item_path(@list, @item), class:"waves-effect waves-light btn"  %> |

<%= link_to 'Delete list', list_item_path(@list, @item), method: :delete, data: {confirm: 'Really Delete?'}, class:"waves-effect waves-light btn" %>
<br />
<%= link_to 'Back to list', list_path(@list), class:"waves-effect waves-light btn"  %>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BucketList</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= button_to 'Log Out', destroy_user_session_path, method: :delete %>
    <%= yield %>
  </body>
</html>

app/views/lists/_list_form.html.erb
<ul>
	<% @list.errors.full_messages.each do |error| %>
		<li><%= error %></li>
	<% end %>
</ul>

<%= form_for @list do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<br />
	<%= f.label :place %>
	<%= f.select :place, ['United States', 'Canada', 'Italy', 'Brazil', 'Germany', 'Australia', 'New Zealand', 'Africa', 'Norway', 'United Kingdom', 'Thailand'] %>
	<br /> 
		<%= f.label :description %>
		<%= f.text_field :description %>
	<br />
		<%= f.label :completed %>
		<%= f.check_box :completed %>

	<%= f.submit %>
<% end %>

app/views/lists/edit.html.erb
<h1>Edit List</h1>

<%= render(partial: 'list_form') %>

<%= link_to 'return to all the lists', lists_path %>
<br />

<%= link_to 'delete lists', list_path(@list), method: :delete %>s

app/views/lists/index.html.erb
<h1 class="center-align indigo-text text-darken-4"">Bucket Lists index</h1>
<% @lists.each do |list| %>
	<%= list.title %>
	<%= link_to "Show list", list_path(list), class:"waves-effect waves-light btn" %>
	<br />
<% end %>
<hr />
<%= link_to "Create List", new_list_path %>

<div>
	<% if @lists.any? %>
	  <div class="row">
			<% @lists.each do |list| %>
	      <div class="col s12 m4">
	        <div class="card">
	          <div class="card-image">
	            <img src="assets/images.jpg">
	            <span class="card-title">
								<%= link_to list.title, list_path(list) %>
							</span>
	          </div>
	          <div class="card-content">
	            <p>This is a beautiful destination where all your dreams come true. With Just the  selection of a button.</p>
	          </div>
	          <div class="card-action">
	            <a href="#">see informations on the list.</a>
	          </div>
	        </div>
	      </div>
	      
			<% end %>
	  </div>
	<% else %>
	<% end %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render(partial: 'list_form') %>

<%= link_to 'return to lists', lists_path %>

app/views/lists/show.html.erb
<div class="hero">
  <nav>
    <div class="nav-wrapper">
      <div class="col s12">
        <a href= <%=lists_path %> class="breadcrumb">All lists</a>
        <a href= <%=list_path(@list) %> class="breadcrumb">Second</a>
      </div>
    </div>
  </nav>


<h1><%= @list.title %></h1>
<p>Description: <%= @list.description %></p>
<p>Location: <%= @list.place %></p>
<p>Completed: <%= @list.completed %></p>
<!--  -->
<div class="primary-nav">
<% @items.each do |item| %>
		<%= item.name %>
		<%= link_to "Show Item", list_item_path(@list, item), class:"waves-effect waves-light btn" %>
		<br />
	<% end %>

	<%= link_to "Add Item to List", new_list_item_path(@list), class:"waves-effect waves-light btn" %> |
</div>
<div class='primary-footer'>
<%= link_to "Add list", new_list_path, class:"waves-effect waves-light btn" %> |
<%= link_to "Edit list", edit_list_path(@list), class:"waves-effect waves-light btn" %>
<%= link_to "Delete List", list_path(@list), method: :delete, class:"waves-effect waves-light btn" %> |
<%= link_to "Back To All Lists", lists_path, class:"waves-effect waves-light btn" %>
</div>